[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
OptControl = "8656af21-ed27-44c9-a769-f8a264997c88"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Stipple = "4acbeb90-81a0-11ea-1966-bdaff8155998"
StipplePlotly = "ec984513-233d-481d-95b0-a3b58b97af2b"
StippleUI = "a3c5d34a-b254-4859-a8fa-b86abb7e84a3"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Genie = "4"
Stipple = "0.23"
StipplePlotly = "0.11"
StippleUI = "0.18"
julia = "1.7"
OptControl = "0.3.0"
